/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 5,
      "expectedClauses": [
        "parse-async-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        71
      ]
    },
    {
      "id": "select-error-violations",
      "description": "ERROR violations in select",
      "functionName": "select",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        20
      ]
    },
    {
      "id": "insert-error-violations",
      "description": "ERROR violations in insert",
      "functionName": "insert",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        33,
        33
      ]
    },
    {
      "id": "rpc-error-violations",
      "description": "ERROR violations in rpc",
      "functionName": "rpc",
      "minViolations": 1,
      "expectedClauses": [
        "rpc-error"
      ],
      "severity": "error",
      "approximateLines": [
        71,
        71
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 8,
      "max": 8
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
