/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 20,
      "expectedClauses": [
        "card-error",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        93
      ]
    },
    {
      "id": "constructEvent-error-violations",
      "description": "ERROR violations in constructEvent",
      "functionName": "constructEvent",
      "minViolations": 2,
      "expectedClauses": [
        "signature-verification-failed",
        "timestamp-too-old"
      ],
      "severity": "error",
      "approximateLines": [
        66,
        66
      ]
    },
    {
      "id": "confirm-error-violations",
      "description": "ERROR violations in confirm",
      "functionName": "confirm",
      "minViolations": 4,
      "expectedClauses": [
        "card-error",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        75,
        75
      ]
    },
    {
      "id": "retrieve-error-violations",
      "description": "ERROR violations in retrieve",
      "functionName": "retrieve",
      "minViolations": 4,
      "expectedClauses": [
        "resource-not-found",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        84,
        84
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 30,
      "max": 30
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
