/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "Client-login-error-violations",
      "description": "ERROR violations in Client.login",
      "functionName": "Client.login",
      "minViolations": 3,
      "expectedClauses": [
        "discord-client-login-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        341,
        346
      ]
    },
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 9,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        36,
        384
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 9,
      "max": 9
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
