/**
 * Expected test output
 * Auto-generated by: npm run test:fixtures:generate
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [],
  "summary": {
    "expectedErrorCount": { "min": 0, "max": 0 },
    "expectedWarningCount": { "min": 0, "max": 0 },
    "expectedInfoCount": { "min": 0, "max": 0 }
  },
  "pending": true,
  "pendingReason": "Analyzer does not yet support callback pattern detection"
};
