/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 1,
      "expectedClauses": [
        "messages-create-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        125,
        125
      ]
    },
    {
      "id": "validateRequest-error-violations",
      "description": "ERROR violations in validateRequest",
      "functionName": "validateRequest",
      "minViolations": 1,
      "expectedClauses": [
        "webhook-no-signature-validation"
      ],
      "severity": "error",
      "approximateLines": [
        153,
        153
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
