/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "get-violations",
      "description": "Violations in get",
      "functionName": "get",
      "minViolations": 9,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "error",
      "approximateLines": [
        22,
        150
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 6,
      "max": 6
    },
    "expectedWarningCount": {
      "min": 3,
      "max": 3
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
