/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-violations",
      "description": "Violations in get",
      "functionName": "get",
      "minViolations": 20,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "error",
      "approximateLines": [
        13,
        112
      ]
    },
    {
      "id": "post-violations",
      "description": "Violations in post",
      "functionName": "post",
      "minViolations": 5,
      "expectedClauses": [
        "error-4xx-5xx",
        "network-failure",
        "rate-limited-429"
      ],
      "severity": "warning",
      "approximateLines": [
        69,
        102
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 12,
      "max": 12
    },
    "expectedWarningCount": {
      "min": 13,
      "max": 13
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
