/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 3,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        65,
        232
      ]
    },
    {
      "id": "createClient-error-violations",
      "description": "ERROR violations in createClient",
      "functionName": "createClient",
      "minViolations": 8,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        244
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 2,
      "expectedClauses": [
        "connect-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        247,
        248
      ]
    },
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 2,
      "expectedClauses": [
        "get-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        251,
        252
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 12,
      "max": 12
    },
    "expectedWarningCount": {
      "min": 3,
      "max": 3
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
