/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 5,
      "expectedClauses": [
        "parse-async-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        26,
        130
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 4,
      "expectedClauses": [
        "card-error",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        130,
        130
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
