/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "create-violations",
      "description": "Violations in create",
      "functionName": "create",
      "minViolations": 20,
      "expectedClauses": [
        "card-error",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        93
      ]
    },
    {
      "id": "confirm-violations",
      "description": "Violations in confirm",
      "functionName": "confirm",
      "minViolations": 4,
      "expectedClauses": [
        "card-error",
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        75,
        75
      ]
    },
    {
      "id": "retrieve-violations",
      "description": "Violations in retrieve",
      "functionName": "retrieve",
      "minViolations": 3,
      "expectedClauses": [
        "rate-limit-error",
        "authentication-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        84,
        84
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 27,
      "max": 27
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
