/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "create-warning-violations",
      "description": "WARNING violations in create",
      "functionName": "create",
      "minViolations": 2,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        52,
        75
      ]
    },
    {
      "id": "retrieve-warning-violations",
      "description": "WARNING violations in retrieve",
      "functionName": "retrieve",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        130,
        130
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 3,
      "max": 3
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
