/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 7,
      "expectedClauses": [
        "invalid-request-error",
        "authentication-error",
        "rate-limit-error",
        "payment-declined",
        "idempotency-conflict",
        "server-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        198,
        198
      ]
    },
    {
      "id": "create-warning-violations",
      "description": "WARNING violations in create",
      "functionName": "create",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        221,
        221
      ]
    },
    {
      "id": "list-error-violations",
      "description": "ERROR violations in list",
      "functionName": "list",
      "minViolations": 3,
      "expectedClauses": [
        "authentication-error",
        "rate-limit-error",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        250,
        250
      ]
    },
    {
      "id": "list-warning-violations",
      "description": "WARNING violations in list",
      "functionName": "list",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        259,
        259
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 10,
      "max": 10
    },
    "expectedWarningCount": {
      "min": 2,
      "max": 2
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
