/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "createOrder-warning-violations",
      "description": "WARNING violations in createOrder",
      "functionName": "createOrder",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        60,
        60
      ]
    },
    {
      "id": "createCustomer-warning-violations",
      "description": "WARNING violations in createCustomer",
      "functionName": "createCustomer",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        93,
        93
      ]
    },
    {
      "id": "retrieveCustomer-warning-violations",
      "description": "WARNING violations in retrieveCustomer",
      "functionName": "retrieveCustomer",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        120,
        120
      ]
    },
    {
      "id": "list-warning-violations",
      "description": "WARNING violations in list",
      "functionName": "list",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        141,
        141
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 4,
      "max": 4
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
