/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "query-error-violations",
      "description": "ERROR violations in query",
      "functionName": "query",
      "minViolations": 12,
      "expectedClauses": [
        "syntax-error",
        "unique-violation",
        "foreign-key-violation",
        "not-null-violation",
        "connection-error",
        "undefined-table"
      ],
      "severity": "error",
      "approximateLines": [
        129,
        138
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 12,
      "max": 12
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
