/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "connect-violations",
      "description": "Violations in connect",
      "functionName": "connect",
      "minViolations": 4,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        101
      ]
    },
    {
      "id": "query-violations",
      "description": "Violations in query",
      "functionName": "query",
      "minViolations": 24,
      "expectedClauses": [
        "syntax-error",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        116
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 28,
      "max": 28
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
