/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "Client-login-error-violations",
      "description": "ERROR violations in Client.login",
      "functionName": "Client.login",
      "minViolations": 15,
      "expectedClauses": [
        "discord-client-login-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        103
      ]
    },
    {
      "id": "query-error-violations",
      "description": "ERROR violations in query",
      "functionName": "query",
      "minViolations": 30,
      "expectedClauses": [
        "syntax-error",
        "unique-violation",
        "foreign-key-violation",
        "not-null-violation",
        "connection-error",
        "undefined-table"
      ],
      "severity": "error",
      "approximateLines": [
        33,
        116
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 45,
      "max": 45
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
