/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 12,
      "expectedClauses": [
        "pool-exhausted",
        "connection-error",
        "client-not-released"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        101
      ]
    },
    {
      "id": "query-error-violations",
      "description": "ERROR violations in query",
      "functionName": "query",
      "minViolations": 72,
      "expectedClauses": [
        "syntax-error",
        "unique-violation",
        "foreign-key-violation",
        "not-null-violation",
        "connection-error",
        "undefined-table"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        116
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 84,
      "max": 84
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
