/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "connect-violations",
      "description": "Violations in connect",
      "functionName": "connect",
      "minViolations": 3,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        23,
        103
      ]
    },
    {
      "id": "query-violations",
      "description": "Violations in query",
      "functionName": "query",
      "minViolations": 20,
      "expectedClauses": [
        "syntax-error",
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        24,
        123
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 23,
      "max": 23
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
