/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 1,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        108,
        108
      ]
    },
    {
      "id": "auth-error-violations",
      "description": "ERROR violations in auth",
      "functionName": "auth",
      "minViolations": 8,
      "expectedClauses": [
        "missing-clerk-middleware",
        "auth-null-not-checked"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        225
      ]
    },
    {
      "id": "currentUser-error-violations",
      "description": "ERROR violations in currentUser",
      "functionName": "currentUser",
      "minViolations": 5,
      "expectedClauses": [
        "current-user-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        35,
        227
      ]
    },
    {
      "id": "getToken-error-violations",
      "description": "ERROR violations in getToken",
      "functionName": "getToken",
      "minViolations": 2,
      "expectedClauses": [
        "get-token-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        68,
        228
      ]
    },
    {
      "id": "useClerk-error-violations",
      "description": "ERROR violations in useClerk",
      "functionName": "useClerk",
      "minViolations": 2,
      "expectedClauses": [
        "use-clerk-outside-provider"
      ],
      "severity": "error",
      "approximateLines": [
        203,
        217
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 17,
      "max": 17
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
