/**
 * Expected test output for rate-limit-scenario.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "rate-limit-scenario.ts",
  "expectations": [
    {
      "id": "currentUser-error-violations",
      "description": "ERROR violations in currentUser",
      "functionName": "currentUser",
      "minViolations": 11,
      "expectedClauses": [
        "current-user-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        162
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 11,
      "max": 11
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
