/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 1,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        166,
        166
      ]
    },
    {
      "id": "readFile-error-violations",
      "description": "ERROR violations in readFile",
      "functionName": "readFile",
      "minViolations": 22,
      "expectedClauses": [
        "file-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        213
      ]
    },
    {
      "id": "readDirectory-error-violations",
      "description": "ERROR violations in readDirectory",
      "functionName": "readDirectory",
      "minViolations": 12,
      "expectedClauses": [
        "directory-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        69,
        210
      ]
    },
    {
      "id": "writeFile-error-violations",
      "description": "ERROR violations in writeFile",
      "functionName": "writeFile",
      "minViolations": 4,
      "expectedClauses": [
        "permission-denied",
        "directory-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        129,
        189
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 38,
      "max": 38
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
