/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 10,
      "expectedClauses": [
        "parse-async-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        86,
        311
      ]
    },
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 2,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        125,
        141
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 10,
      "max": 10
    },
    "expectedWarningCount": {
      "min": 2,
      "max": 2
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
