/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 9,
      "expectedClauses": [
        "parse-async-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        162
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 5,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        162
      ]
    },
    {
      "id": "create-warning-violations",
      "description": "WARNING violations in create",
      "functionName": "create",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        133,
        133
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 14,
      "max": 14
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
