/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "handleSubmit-warning-violations",
      "description": "WARNING violations in handleSubmit",
      "functionName": "handleSubmit",
      "minViolations": 1,
      "expectedClauses": [
        "empty-catch-block-silent-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        155,
        155
      ]
    },
    {
      "id": "create-warning-violations",
      "description": "WARNING violations in create",
      "functionName": "create",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        16,
        16
      ]
    },
    {
      "id": "update-warning-violations",
      "description": "WARNING violations in update",
      "functionName": "update",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        35,
        35
      ]
    },
    {
      "id": "delete-warning-violations",
      "description": "WARNING violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        54,
        54
      ]
    },
    {
      "id": "findUnique-warning-violations",
      "description": "WARNING violations in findUnique",
      "functionName": "findUnique",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        72,
        72
      ]
    },
    {
      "id": "-transaction-warning-violations",
      "description": "WARNING violations in $transaction",
      "functionName": "$transaction",
      "minViolations": 2,
      "expectedClauses": [
        "deadlock-error",
        "connection-error-in-transaction"
      ],
      "severity": "warning",
      "approximateLines": [
        91,
        91
      ]
    },
    {
      "id": "findUniqueOrThrow-warning-violations",
      "description": "WARNING violations in findUniqueOrThrow",
      "functionName": "findUniqueOrThrow",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error"
      ],
      "severity": "warning",
      "approximateLines": [
        120,
        120
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 8,
      "max": 8
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
