/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "create-violations",
      "description": "Violations in create",
      "functionName": "create",
      "minViolations": 35,
      "expectedClauses": [
        "authentication-error",
        "rate-limit-error",
        "server-error",
        "timeout-error",
        "invalid-request-error"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        107
      ]
    },
    {
      "id": "generate-violations",
      "description": "Violations in generate",
      "functionName": "generate",
      "minViolations": 3,
      "expectedClauses": [
        "authentication-error",
        "rate-limit-error-images",
        "server-error"
      ],
      "severity": "error",
      "approximateLines": [
        67,
        67
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 38,
      "max": 38
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
