/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 14,
      "expectedClauses": [
        "unhandled-promise-rejection",
        "get-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        90
      ]
    },
    {
      "id": "set-error-violations",
      "description": "ERROR violations in set",
      "functionName": "set",
      "minViolations": 6,
      "expectedClauses": [
        "set-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        31,
        107
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 1,
      "expectedClauses": [
        "connect-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        90,
        90
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 21,
      "max": 21
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
