/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 3,
      "expectedClauses": [
        "parse-async-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        56
      ]
    },
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "unhandled-promise-rejection"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        56
      ]
    },
    {
      "id": "set-error-violations",
      "description": "ERROR violations in set",
      "functionName": "set",
      "minViolations": 6,
      "expectedClauses": [
        "unhandled-promise-rejection"
      ],
      "severity": "error",
      "approximateLines": [
        31,
        107
      ]
    },
    {
      "id": "pipeline-error-violations",
      "description": "ERROR violations in pipeline",
      "functionName": "pipeline",
      "minViolations": 4,
      "expectedClauses": [
        "pipeline-results-not-checked",
        "pipeline-exec-unhandled"
      ],
      "severity": "error",
      "approximateLines": [
        43,
        97
      ]
    },
    {
      "id": "multi-error-violations",
      "description": "ERROR violations in multi",
      "functionName": "multi",
      "minViolations": 4,
      "expectedClauses": [
        "watch-null-not-checked",
        "exec-abort-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        58,
        107
      ]
    },
    {
      "id": "subscribe-error-violations",
      "description": "ERROR violations in subscribe",
      "functionName": "subscribe",
      "minViolations": 1,
      "expectedClauses": [
        "subscriber-mode-violation"
      ],
      "severity": "error",
      "approximateLines": [
        68,
        68
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 1,
      "expectedClauses": [
        "connect-promise-unhandled"
      ],
      "severity": "error",
      "approximateLines": [
        90,
        90
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 22,
      "max": 22
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
